name: Build

on: [push, pull_request]

jobs:
  build-android-armv7a:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Build android-armv7a
      run: |
        scripts/build-android-armv7a.sh
    - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: androidbuild
          path: ./build
